include(CompilerFlags/GNU) #use settings from GCC compiler

#set(CMAKE_CXX_FLAGS " --std=c++11 ${CMAKE_CXX_FLAGS}")
#set(CMAKE_CXX_FLAGS_DEBUG " ${CMAKE_CXX_FLAGS_DEBUG}")
#set(CMAKE_CXX_FLAGS_RELEASE " ${CMAKE_CXX_FLAGS_RELEASE}")
#set(CMAKE_CXX_FLAGS_RELWITHDEBINFO " ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
#set(CMAKE_CXX_FLAGS_MINSIZEREL " ${CMAKE_CXX_FLAGS_MINSIZEREL}")