
#ifndef CONSOLELOGGER_EXPORT_H
#define CONSOLELOGGER_EXPORT_H

#ifdef CONSOLELOGGER_STATIC_DEFINE
#  define CONSOLELOGGER_EXPORT
#  define CONSOLELOGGER_NO_EXPORT
#else
#  ifndef CONSOLELOGGER_EXPORT
#    ifdef ConsoleLogger_EXPORTS
        /* We are building this library */
#      define CONSOLELOGGER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CONSOLELOGGER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CONSOLELOGGER_NO_EXPORT
#    define CONSOLELOGGER_NO_EXPORT 
#  endif
#endif

#ifndef CONSOLELOGGER_DEPRECATED
#  define CONSOLELOGGER_DEPRECATED __declspec(deprecated)
#endif

#ifndef CONSOLELOGGER_DEPRECATED_EXPORT
#  define CONSOLELOGGER_DEPRECATED_EXPORT CONSOLELOGGER_EXPORT CONSOLELOGGER_DEPRECATED
#endif

#ifndef CONSOLELOGGER_DEPRECATED_NO_EXPORT
#  define CONSOLELOGGER_DEPRECATED_NO_EXPORT CONSOLELOGGER_NO_EXPORT CONSOLELOGGER_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CONSOLELOGGER_NO_DEPRECATED
#endif

#endif
