
#ifndef RESOURCEMANAGER_EXPORT_H
#define RESOURCEMANAGER_EXPORT_H

#ifdef RESOURCEMANAGER_STATIC_DEFINE
#  define RESOURCEMANAGER_EXPORT
#  define RESOURCEMANAGER_NO_EXPORT
#else
#  ifndef RESOURCEMANAGER_EXPORT
#    ifdef ResourceManager_EXPORTS
        /* We are building this library */
#      define RESOURCEMANAGER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define RESOURCEMANAGER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef RESOURCEMANAGER_NO_EXPORT
#    define RESOURCEMANAGER_NO_EXPORT 
#  endif
#endif

#ifndef RESOURCEMANAGER_DEPRECATED
#  define RESOURCEMANAGER_DEPRECATED __declspec(deprecated)
#endif

#ifndef RESOURCEMANAGER_DEPRECATED_EXPORT
#  define RESOURCEMANAGER_DEPRECATED_EXPORT RESOURCEMANAGER_EXPORT RESOURCEMANAGER_DEPRECATED
#endif

#ifndef RESOURCEMANAGER_DEPRECATED_NO_EXPORT
#  define RESOURCEMANAGER_DEPRECATED_NO_EXPORT RESOURCEMANAGER_NO_EXPORT RESOURCEMANAGER_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define RESOURCEMANAGER_NO_DEPRECATED
#endif

#endif
