#pragma once

#include <MathPrerequisites.h>

#include <Eigen/Dense>

#define UNKNOWNENGINE_ALIGNED_NEW_OPERATOR EIGEN_MAKE_ALIGNED_OPERATOR_NEW

#define UNKNOWNENGINE_ALIGNED_DEFINITION(size) EIGEN_ALIGN_TO_BOUNDARY(size)

#ifdef _MSC_VER
	#define UNKNOWNENGINE_ALIGNED_CLASS(size) UNKNOWNENGINE_ALIGNED_DEFINITION(size) class
#else
	#define UNKNOWNENGINE_ALIGNED_CLASS(size) class UNKNOWNENGINE_ALIGNED_DEFINITION(size)
#endif

#ifdef _MSC_VER
#define UNKNOWNENGINE_ALIGNED_STRUCT(size) UNKNOWNENGINE_ALIGNED_DEFINITION(size) struct
#else
#define UNKNOWNENGINE_ALIGNED_STRUCT(size) struct UNKNOWNENGINE_ALIGNED_DEFINITION(size)
#endif